import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import type { Metadata } from "next";

import { ThemeOptions } from "@mui/material/styles";
import ThemeRegistry from "@/features/ThemeRegistry";
import Topbar from "@/features/Topbar";
import { Box } from "@mui/material";
import CanvasOverlay from "@/features/CanvasOverlay";
import SidePanel from "@/features/SidePanel";
import Providers from "./Providers";
import PagesPanel from "@/features/PagesPanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const themeOptions: ThemeOptions = {
  palette: {
    mode: "dark",
    primary: {
      main: "#1976d2",
    },
    secondary: {
      main: "#f50057",
    },
    background: {
      default: "#02040a",
      paper: "#0d1116",
    },
    text: {
      primary: "#e6edf3",
      secondary: "rgba(230,237,243,0.7)",
      disabled: "rgba(230,237,243,0.7)",
    },
  },
  shape: {
    borderRadius: 8,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>
          <Providers>
            <Topbar />
            <Box display="flex">
              <PagesPanel />
              <Box sx={{ height: "calc(100dvh - 64px)", width: "100%", overflow: "auto" }}>
                {children}
              </Box>
              <SidePanel />
            </Box>
            <CanvasOverlay />
          </Providers>
        </ThemeRegistry>
      </body>
    </html>
  );
}
